path.config: /usr/share/logstash/pipeline
xpack.monitoring.elasticsearch.url: http://elastic:9200
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: changeme
xpack.monitoring.enabled: false
